# Generated by Django 5.0.3 on 2024-03-26 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.ImageField(blank=True, upload_to='signatures/')),
                ('signer', models.CharField(blank=True, default='', max_length=100)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifier', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='esign.signeddocument')),
            ],
        ),
    ]
